[package]
name = "bevy-butler-proc-macro"
version = "0.1.0"
edition = "2024"
description = "Procedural macro definitions for bevy-butler"
license = "MIT OR Apache-2.0"
repository = "https://github.com/TGRCdev/bevy-butler"

[lib]
proc-macro = true

[dependencies]
inventory = "0.3.16"
quote = "1.0.38"
syn = { version = "2.0.95", features = ["full"] }
proc-macro-crate = "3.2.0"
proc-macro2 = "1.0.92"