[workspace]
resolver = "2"
members = [
    "bevy-butler-proc-macro",
    "bevy-butler"
]

[workspace.package]
exclude = [".direnv/", ".vscode/", "Cargo.lock", "*.nix", "flake.lock", ".envrc", ".github/"]
