[package]
name = "bevy-butler"
version = "0.1.0"
edition = "2021"
categories = ["game-development", "rust-patterns"]
description = "A crate for making Bevy systems more self-documenting"
exclude = [".direnv/", "*.nix", "flake.lock", ".envrc"]
repository = "https://github.com/TGRCdev/bevy-butler"
keywords = ["game", "gamedev", "bevy", "systems", "macro"]
license = "MIT OR Apache-2.0"

[workspace]
members = [
    "bevy-butler-core",
    "bevy-butler-proc-macro",
]

[dependencies]
bevy-butler-proc-macro = { path = "./bevy-butler-proc-macro", version = "0.1.0" }
bevy-butler-core = { path = "./bevy-butler-core", version = "0.1.0" }

[dev-dependencies]
bevy = { version = "0.15.1", default-features = false }
bevy_app = { version = "0.15.1", default-features = false }
bevy_ecs = { version = "0.15.1", default-features = false }
bevy_internal = { version = "0.15.1", default-features = false }
