[package]
name = "bevy-butler"
version = "1.0.0"
edition = "2021"
categories = ["game-development", "rust-patterns"]
description = "A crate for making Bevy systems more self-documenting"
exclude = [".direnv/", ".vscode/", "Cargo.lock", "*.nix", "flake.lock", ".envrc", ".github/"]
repository = "https://github.com/TGRCdev/bevy-butler"
keywords = ["game", "gamedev", "bevy", "systems", "macro"]
license = "MIT OR Apache-2.0"
rust-version = "1.81.0" # Determined by cargo-msrv


[dependencies]
bevy-butler-proc-macro = { path = "./bevy-butler-proc-macro", version = "1.0.0" }

[dev-dependencies]
bevy_app = { version = "0.15.1", default-features = false }
