[package]
name = "bevy-butler"
version = "0.4.0"
edition = "2021"
categories = ["game-development", "rust-patterns"]
description = "A crate for making Bevy systems more self-documenting"
exclude = [".direnv/", ".vscode/", "Cargo.lock", "*.nix", "flake.lock", ".envrc", ".github/"]
repository = "https://github.com/TGRCdev/bevy-butler"
keywords = ["game", "gamedev", "bevy", "systems", "macro"]
license = "MIT OR Apache-2.0"
rust-version = "1.81.0" # Determined by cargo-msrv

[package.metadata.docs.rs]
all-features = true

[workspace]
members = [
    "bevy-butler-proc-macro",
]

[dependencies]
bevy-butler-proc-macro = { path = "./bevy-butler-proc-macro", version = "0.4.0" }
bevy_app = { version = "0.15.1", default-features = false }
bevy_ecs = { version = "0.15.1", default-features = false }
bevy_log = { version = "0.15.1", default-features = false }
bevy_utils = { version = "0.15.1", default-features = false }
linkme = "0.3.31"

[dev-dependencies]
bevy = { version = "0.15.1", default-features = false }

[features]
nightly = ["bevy-butler-proc-macro/nightly", "linkme/used_linker"]
