name: Rust

on: ["push", "pull_request"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run bevy-butler tests
      run: cargo test --verbose
  build-nightly:
    name: Build Nightly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - name: Build
      run: cargo +nightly build --verbose
    - name: Run bevy-butler tests
      run: cargo +nightly test --verbose
  build-inventory:
    name: Build (inventory)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --features inventory --verbose
    - name: Run bevy-butler tests
      run: cargo test --features inventory --verbose
  build-inventory-nightly:
    name: Build Nightly (inventory)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - name: Build
      run: cargo +nightly build --features inventory --verbose
    - name: Run bevy-butler tests
      run: cargo +nightly test --features inventory --verbose
  check-src:
    name: Check Source Changed
    runs-on: ubuntu-latest
    if: ${{
      github.ref == 'refs/heads/main' &&
      github.event_name == 'push' &&
      ! startsWith(github.event.head_commit.message, '[no publish]') }}
    outputs:
      src-changed: ${{ steps.changes.outputs.src }}
    steps:
      - uses: actions/checkout@v4
      - name: Paths Changes Filter
        id: changes
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            src:
              - 'bevy-butler/src/**'
              - 'bevy-butler/Cargo.toml'
              - 'bevy-butler/build.rs'
              - 'bevy-butler-proc-macro/src/**'
              - 'bevy-butler-proc-macro/Cargo.toml'
              - 'Cargo.toml'
  publish-prerelease:
    name: Publish Pre-release
    needs: [build, build-nightly, build-inventory, build-inventory-nightly, check-src]
    if: needs.check-src.outputs.src-changed == 'true'
    uses: ./.github/workflows/prerelease.yml
    permissions:
      contents: write
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
