name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run bevy-butler tests
      run: cargo test --verbose
  build-nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - name: Build
      run: cargo +nightly build --verbose
    - name: Run bevy-butler tests
      run: cargo +nightly test --verbose
  build-inventory:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --features inventory --verbose
    - name: Run bevy-butler tests
      run: cargo test --features inventory --verbose
  build-inventory-nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - name: Build
      run: cargo +nightly build --features inventory --verbose
    - name: Run bevy-butler tests
      run: cargo +nightly test --features inventory --verbose
  build-wasm:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    - uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'
    - name: Run bevy-butler tests
      run: wasm-pack test --node --verbose
